const swaggerAutogen = require('swagger-autogen')()

const doc = {
    info: {
        version: "0.0.1",
        title: "Service timer api",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3001",
    basePath: "",
    schemes: ['http', 'https'],
    consumes: ['application/json'],
    produces: ['application/json'],
    definitions: {}
}

const outputFile = __dirname + '/swagger_output.json'
const endpointsFiles = [
    __dirname + '/routes/get.ts',
    //__dirname + '/routes/delete.ts',

]

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    console.log('Adding base documentation')
    //require('./index')           // Your project's root file
})
